apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
   
  labels:
    io.kompose.service: meal-planning-ui
  name: meal-planning-ui
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8085
      targetPort: 3000
  selector:
    io.kompose.service: meal-planning-ui
status:
  loadBalancer: {}
