apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
   
  labels:
    io.kompose.service: profile-database
  name: profile-database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: profile-database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
       
      labels:
        io.kompose.service: profile-database
    spec:
      containers:
        - image: mongo:latest
          name: profile-database
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: profile-database-mongo
      restartPolicy: Always
      volumes:
        - name: profile-database-mongo
          persistentVolumeClaim:
            claimName: profile-database-mongo
status: {}
