apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   
  labels:
    io.kompose.service: profile-database-mongo
  name: profile-database-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
