apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: user-profile
  name: recipe-suggestion
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: recipe-suggestion
status:
  loadBalancer: {}
