apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: recipe-suggestion
  name: recipe-suggestion
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recipe-suggestion
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: recipe-suggestion
    spec:
      containers:
        - image: fvossebeld/recipesuggestion:latest
          name: recipe-suggestion
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
