apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
   
  labels:
    io.kompose.service: shoppinglistoptimization
  name: shoppinglistoptimization
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: shoppinglistoptimization
status:
  loadBalancer: {}
