apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
   
  labels:
    io.kompose.service: activemq
  name: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: activemq
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
       
      labels:
        io.kompose.service: activemq
    spec:
      containers:
        - image: rmohr/activemq:latest
          name: activemq
          ports:
            - containerPort: 8161
            - containerPort: 61616
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: activemq-claim0
            - mountPath: /var/log/activemq
              name: activemq-claim1
      restartPolicy: Always
      volumes:
        - name: activemq-claim0
          persistentVolumeClaim:
            claimName: activemq-claim0
        - name: activemq-claim1
          persistentVolumeClaim:
            claimName: activemq-claim1
status: {}
