apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
   
  labels:
    io.kompose.service: jumbopriceservice
  name: jumbopriceservice
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8080
  selector:
    io.kompose.service: jumbopriceservice
status:
  loadBalancer: {}
