//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.23 at 07:17:33 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/api/events/priceinquiry", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.shoppinglistoptimization.integrations.priceinquiry;
