//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.18 at 03:07:54 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/api/events/shoppinglistrequest", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.shoppinglistoptimization.integrations.shoppinglistrequest;
