@startuml "get suggestion"
actor       user       as user
participant "User Interface" as ui
participant "Meal Planning" as mealplan
queue       "Suggestion queue"       as q1
participant "meal suggestion service" as suggest
participant "user profile service" as profile

user -> ui : Refresh suggestion
activate ui
ui -> mealplan : /updateRecipes
activate mealplan
mealplan -> q1 : generate # of suggestions
activate q1
deactivate q1
deactivate mealplan
deactivate ui
== ==
q1 -> suggest : handle request
activate q1
activate suggest
deactivate q1
suggest -> profile : retrieve preference
activate profile
deactivate profile
suggest -> suggest : generate suggestions
activate suggest
deactivate suggest
suggest -> q1 : return request
activate q1
deactivate suggest
deactivate q1
== ==
q1 -> mealplan : return suggestions
activate q1
activate mealplan
mealplan -> mealplan : process suggestions
activate mealplan
deactivate mealplan
deactivate mealplan
deactivate q1
== ==
ui -> mealplan : /retrieveMeals
activate ui
activate mealplan
mealplan -> mealplan : get suggestions from database
activate mealplan
deactivate mealplan
deactivate mealplan
deactivate ui
@enduml