//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.18 at 11:58:53 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/api/events/reciperequest", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.mealplanningservice.integration.reciperequest;
